# Pre-commit hooks for code quality
# Install: pip install pre-commit
# Setup: pre-commit install
# Run: pre-commit run --all-files

repos:
  # Ruff - Fast Python linter and formatter (replaces black, isort, and more)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.9
    hooks:
      # Run the linter first
      - id: ruff
        args: ['--fix', '--exit-non-zero-on-fix']
      # Then run the formatter
      - id: ruff-format

  # MyPy - Static type checker
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        additional_dependencies: [types-requests, types-PyYAML]
        args: ['--ignore-missing-imports', '--no-strict-optional']
        files: ^libs/

  # Standard pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-json
      - id: check-merge-conflict
      - id: check-ast
      - id: debug-statements
      - id: detect-private-key

  # Docstring coverage
  - repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks:
      - id: interrogate
        args: ['-vv', '--fail-under=80', '--ignore-init-module', '--ignore-init-method']
        files: ^libs/
        additional_dependencies: [setuptools]

  # Security checks
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.6
    hooks:
      - id: bandit
        args: ['-ll', '-r', 'libs/']
        files: ^libs/

  # Unit test runner (fast feedback)
  - repo: local
    hooks:
      - id: unit-tests-check
        name: Run fast unit tests
        entry: python -m pytest tests/unit/ -x --tb=short -q --disable-warnings -k "not slow"
        language: system
        pass_filenames: false
        stages: [pre-commit]

# Configuration for specific tools
default_language_version:
  python: python3.12

# Only run on Python files by default
files: \.py$
exclude: |
  (?x)^(
    .*\.egg-info/|
    \.git/|
    \.tox/|
    dist/|
    build/|
    __pycache__/|
    \.pytest_cache/|
    htmlcov/|
    \.coverage|
    \.mypy_cache/|
    \.ruff_cache/|
    test-results/|
    mock_server/static/|
    docs/_build/
  )