# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
  python: python3.12

repos:
  # Basic file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=1000']  # 1MB limit
      - id: check-merge-conflict
      - id: mixed-line-ending
        args: ['--fix=lf']  # Convert to LF automatically

  # Black - Code formatter CHECK ONLY (no auto-fix)
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        args: ['--check', '--diff']  # Check only, show differences
        language_version: python3.12
        name: black (check formatting)
        description: 'Black: Check Python code formatting (no auto-fix)'

  # Ruff - Fast Python linter (auto-fix safe issues only)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.0
    hooks:
      - id: ruff
        args: ['--fix', '--exit-non-zero-on-fix', '--show-fixes', '--config', '.ruff.toml']  # Fix safe issues, show what was fixed
        name: ruff (auto-fix safe issues)
        description: 'Ruff: Fast Python linter with safe auto-fixes'
      # Ruff-format disabled to avoid conflicts with Black
      # - id: ruff-format
      #   args: ['--check', '--diff']  # Check formatting only
      #   name: ruff-format (check formatting)
      #   description: 'Ruff: Check Python formatting (no auto-fix)'

exclude: '^(\.git|\.mypy_cache|\.pytest_cache|\.ruff_cache|__pycache__|build|dist|\.venv|venv)'

# Performance optimizations
ci:
  autofix_prs: false
  autoupdate_schedule: weekly
