# 제외할 디렉토리
exclude = [
    ".git",
    ".venv",
    "__pycache__",
    "build",
    "dist",
    "mock_server/openapi_spec.json",
]

[lint]
# 기본 규칙 선택
select = ["E", "F", "I"]

# 무시할 규칙들
ignore = [
    "E501",  # Line too long 무시
    "E402",  # Module import not at top of file 무시 (테스트 파일에서 필요)
    "E722",  # Bare except 무시
    "F841",  # 테스트 파일의 미사용 변수 허용
]

# 파일별 무시 규칙
[lint.per-file-ignores]
"tests/**/*.py" = ["F841"]  # 테스트 파일에서 미사용 변수 허용
"**/test_*.py" = ["F841"]   # test_로 시작하는 파일에서 미사용 변수 허용

# Import 정렬 설정
[lint.isort]
known-first-party = ["src", "libs", "tests"]
