global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'billing-test-monitor'

# Alertmanager configuration (optional)
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Load rules once and periodically evaluate them
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# Scrape configurations
scrape_configs:
  # Billing test metrics
  - job_name: 'billing-test'
    static_configs:
      - targets: ['host.docker.internal:9464']  # pytest-opentelemetry metrics port
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Mock server metrics (if instrumented)
  - job_name: 'mock-server'
    static_configs:
      - targets: ['host.docker.internal:5000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
