BASE_BILLING_URL = "https://billingtest.internal.com"
BASE_METERING_URL = "https://meteringtest.internal.com"
BASE_CAP_URL = "https://cabtest.internal.com"

METERING_URL = f"{BASE_METERING_URL}/billing/meters"
METERING_ADMIN_URL = f"{BASE_METERING_URL}/billing/admin"
BILLING_ADMIN_URL = f"{BASE_BILLING_URL}/billing/admin"
BILLING_CONSOLE_URL = f"{BASE_BILLING_URL}/billing/"
BILLING_CONSOLE_V5 = f"{BASE_BILLING_URL}/billing/v5.0"
BILLING_QA_URL = f"{BASE_BILLING_URL}/billing/qa"
ALPHA_CAB_URL = f"{BASE_CAP_URL}/api/projects/"
CREDIT_COUPON_URL = f"{BASE_BILLING_URL}/billing/coupons/"
CREDIT_GIVE_URL = f"{BASE_BILLING_URL}/billing/admin/campaign/"
CREDIT_HISTORY_URL = f"{BASE_BILLING_URL}/billing/credits/history"
