# Cloudflare Pages Configuration for Next.js Static Export
# This file is optional - Cloudflare Pages auto-detects Next.js

name = "billing-calculator"
pages_build_output_dir = "out"

# Compatibility settings
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Build configuration (Cloudflare Pages will use these)
[build]
command = "npm run build"
cwd = ""

# Environment variables for production
[env.production]
vars = { NODE_ENV = "production" }
